### ISSUE TITLE
does it have range function?

### ISSUE THREAD

**Issue by slim-python** [linmasahiro/vue3-datepicker-lite#1]
Hi, can i set a date range with this?
like from October 14 2019 to October 15, 2020?

**Comment by linmasahiro** [comment]
> Hi, can i set a date range with this?
> like from October 14 2019 to October 15, 2020?

hi, i added from attribute and to attribute on version 1.4.0 and updated readme.
if you want to use the range function, upgrade to 1.4.0 please.
