### ISSUE TITLE
Default value not working

### ISSUE THREAD

**Issue by XanderTenBoden** [linmasahiro/vue3-datepicker-lite#11]
Hello!

I'm trying to set the default value of the date picker. Looking in the code, it seems that the date is being added to the div that is surrounding the text input. However, the input field itself does not display the date. Do you have any clue how to fix this?

Cheers!

My code:
```
<DatepickerLite
        :name-attr="name"
        class-attr="form-control" :class="errors.length > 0 ? 'is-invalid' : ''"
        :value="modelValue"     <=== "2020-12-30"
        :locale="localeSettings"
        @valueChanged="updateValue"
/>

.....

const localeSettings = computed(() => {
        return {
          format: props.displayFormat, // "DD-MM-YYYY"
          weekday: [
            i18n.t('datepicker.mon'),
            i18n.t('datepicker.tue'),
            i18n.t('datepicker.wed'),
            i18n.t('datepicker.thu'),
            i18n.t('datepicker.fri'),
            i18n.t('datepicker.sat'),
            i18n.t('datepicker.sun'),
          ],
          startsWeeks: 1,
          todayBtn: i18n.t('datepicker.today'),
          clearBtn: i18n.t('datepicker.clear'),
          closeBtn: i18n.t('datepicker.close'),
        }
      })
```

Screenshot:
<img width="1385" alt="Screenshot 2021-02-14 at 22 25 57" src="https://user-images.githubusercontent.com/6901151/107889584-fcb95c00-6f13-11eb-8823-4c606248af83.png">

**Comment by linmasahiro** [comment]
> props.displayFormat

hi
your default value format need change to 「30-12-2020」
value and localeSettings.format need to same format.

**Comment by XanderTenBoden** [comment]
I fixed this by changing:

`:value="modelValue"`

to:
`:value-attr="modelValue"`
