### ISSUE TITLE
Make date field a button

### ISSUE THREAD

**Issue by sknick** [linmasahiro/vue3-datepicker-lite#13]
It would be nice if the part of the component that you click to show the calendar was a simple button. Right now, it's a text field, but this is annoying when you're on a mobile device or smart TV as clicking on it results in the keyboard coming up.

**Comment by linmasahiro** [comment]
> It would be nice if the part of the component that you click to show the calendar was a simple button. Right now, it's a text field, but this is annoying when you're on a mobile device or smart TV as clicking on it results in the keyboard coming up.

thank you for idea.
i never think about action on smart TV before.
but it's easy to support. so
i added button-type option to ver 1.8.8, if option is true, to be button.
You can try it,if you are :)

**Comment by sknick** [comment]
Beautiful! Works like a champ. If you want to see your component in action, look at [http://raceday.watch](http://raceday.watch).

**Comment by linmasahiro** [comment]
> Beautiful! Works like a champ. If you want to see your component in action, look at http://raceday.watch.

Wow! It's so cool.  Use it and I will not forget to watch MotoGP, Haha.
