### ISSUE TITLE
Append to body

### ISSUE THREAD

**Issue by bryan-andersen** [linmasahiro/vue3-datepicker-lite#14]
It would be helpful if there were a prop that would allow the date panel to be placed above all elements instead of inline. This would alleviate a case as such that the datepicker might be hidden/cut off if placed in a fixed/sticky container with a height that is lesser than the size of the date panel and cannot overlap other sibling containers in the whole of the layout. Example of an issue I ran into attached.
![unknown](https://user-images.githubusercontent.com/31540787/113692682-c7bbc100-969b-11eb-8132-7cfa8da2d83d.png)
.

**Comment by linmasahiro** [comment]
> It would be helpful if there were a prop that would allow the date panel to be placed above all elements instead of inline. This would alleviate a case as such that the datepicker might be hidden/cut off if placed in a fixed/sticky container with a height that is lesser than the size of the date panel and cannot overlap other sibling containers in the whole of the layout. Example of an issue I ran into attached.
> ![unknown](https://user-images.githubusercontent.com/31540787/113692682-c7bbc100-969b-11eb-8132-7cfa8da2d83d.png)
> .

Hi, i try to made a sample to check it. but it's good work like this. Maybe you can share your template for me to make check that.
![unknown](https://im3.ezgif.com/tmp/ezgif-3-1bbd17a27bf0.gif)


StyleSheet:
```
.main-container{border:solid 10px green; height: 500px;}
.main-header{background:#aaa;  height: 50px;}
.main-header{position:-webkit-sticky; position:sticky; top:0;}
.main-content{background:rgb(129, 60, 60);  color:white; height: 400px;}
.main-footer{background:rgb(98, 75, 230);  color:white; height: 50px;}

```

HTML:
```
<main class="main-container">
    <header class="main-header">
      <datepicker-lite
      ......
      ></datepicker-lite>
    </header>
    <div class="main-content">CONTENT</div>
    <footer class="main-footer">FOOTER</footer>
  </main>
```

**Comment by linmasahiro** [comment]
I am closing this issue. If you still have problem, reopen the issue.
