### ISSUE TITLE
Month names instead of numbers

### ISSUE THREAD

**Issue by oleksandr-holub** [linmasahiro/vue3-datepicker-lite#15]
Is it possible change month numbers 1-12 to words January, February etc.?
![Снимок экрана 2021-04-12 в 15 46 22](https://user-images.githubusercontent.com/40006036/114396734-8c8f2580-9ba6-11eb-8b6f-40f3c0ab7b3e.png)

**Comment by linmasahiro** [comment]
> Is it possible change month numbers 1-12 to words January, February etc.?
> ![Снимок экрана 2021-04-12 в 15 46 22](https://user-images.githubusercontent.com/40006036/114396734-8c8f2580-9ba6-11eb-8b6f-40f3c0ab7b3e.png)

Hi, I added months-option to locale-options. So you can use it to change Month name on version 1.8.9 now!

```
{
        format: "YYYY/MM/DD",
        weekday: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        months: ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"],
        startsWeeks: 0,
        todayBtn: "Today",
        clearBtn: "Clear",
        closeBtn: "Close",
}
```

enjoy it.
