### ISSUE TITLE
Option to Disable icons for todayBtn, clearBtn and closeBtn

### ISSUE THREAD

**Issue by mashmoom** [linmasahiro/vue3-datepicker-lite#16]
Need an option / flag to disable icons for todayBtn, clearBtn and closeBtn.

**Comment by linmasahiro** [comment]
> Need an option / flag to disable icons for todayBtn, clearBtn and closeBtn.

HI @mashmoom 
I added new options on your hope! update to 1.9.0 plz.

**Comment by mashmoom** [comment]
Marking the issue closed. Available in 1.9.0.
