### ISSUE TITLE
A feature to type the date in the text input field(enable / disable)

### ISSUE THREAD

**Issue by mashmoom** [linmasahiro/vue3-datepicker-lite#17]
An option to let the input field editable to type in the date.  In the format from the locale provided with slash in between.

**Comment by mashmoom** [comment]
Some users would like to type in the date if it is an input type. Ex: Like changing a year than scrolling through the list. While typing the date format should remain the same, the slash / should be fixed in position.

Thank you

**Comment by linmasahiro** [comment]
> Some users would like to type in the date if it is an input type. Ex: Like changing a year than scrolling through the list. While typing the date format should remain the same, the slash / should be fixed in position.
> 
> Thank you

OK, I understand your needs. I try to add this function to next version. 
But I am busy on this weekend, so wait some days plz.
By the way, maybe you can check #16 first! ;)

**Comment by mashmoom** [comment]
Thank you very much linmasahiro. 
No hurries.

**Comment by linmasahiro** [comment]
> Thank you very much linmasahiro.
> No hurries.

Hi, @mashmoom . I added auto-complate slash function to the input field.
upgrade to ver1.9.1 and enjoy it.

[DEMO](https://linmasahiro.github.io/vue3-datepicker-lite/dist/)

**Comment by mashmoom** [comment]
The feature looks beautiful. I was wondering how the on focus show calendar and on change type text would be handled. The feature is looking awesome. 

Verified in version 1.9.1.

Closing the ticket.
