### ISSUE TITLE
  :years-range="10" not working,kindly check

### ISSUE THREAD

**Issue by ravindrayr** [linmasahiro/vue3-datepicker-lite#18]
<datepicker-lite
              :id-attr="fromDatepickerSetting.id"
              :name-attr="fromDatepickerSetting.name"
              :class-attr="fromDatepickerSetting.class"
              :value-attr="fromDatepickerSetting.value"
              :autocomplete-attr="fromDatepickerSetting.autocomplete"
              :placeholder-attr="fromDatepickerSetting.placeholder"
              :is-button-type="fromDatepickerSetting.isButtonType"
              :year-minus="fromDatepickerSetting.yearMinus"
              :years-range="10"
              :from="fromDatepickerSetting.fromDate"
              :to="fromDatepickerSetting.toDate"
              :locale="fromDatepickerSetting.locale"
              :disableInput="fromDatepickerSetting.disableInput"
              @value-changed="fromDatepickerSetting.changeEvent"
              ref="fromDateTemplateRef"
              @input="checkStartDate()"
            ></datepicker-lite>

**Comment by linmasahiro** [comment]
Hi @ravindrayr 
I try this sample it's good working. Maybe you can give me more details. Thanks.
```
<datepicker-lite
    :id-attr="datepickerSetting.id"
    :name-attr="datepickerSetting.name"
    :class-attr="datepickerSetting.class"
    :value-attr="datepickerSetting.value"
    :placeholder-attr="datepickerSetting.placeholder"
    :is-button-type="datepickerSetting.isButtonType"
    :locale="datepickerSetting.locale"
    :year-minus="datepickerSetting.yearMinus"
    :years-range="10"
    :from="datepickerSetting.fromDate"
    :to="datepickerSetting.toDate"
    :disabled-date="datepickerSetting.disabledDate"
    @value-changed="datepickerSetting.changeEvent"
    :disable-input="datepickerSetting.disableInput"
    :show-bottom-button="false"
  ></datepicker-lite>
```
```
const datepickerSetting = {
      id: "birthday3",
      name: "birthday3",
      class: "myDateInput",
      value: "2020/10/01",
      placeholder: "Select",
      isButtonType: true,
      yearMinus: 0,
      fromDate: "2020/02/10",
      toDate: "",
      disabledDate: [],
      locale: {
        format: "YYYY/MM/DD",
        weekday: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        months: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
        startsWeeks: 0,
        todayBtn: "Today",
        clearBtn: "Clear",
        closeBtn: "Close",
      },
      changeEvent: (value) => {
        console.log(value + " selected!");
      },
      disableInput: false,
    };
```

**Comment by ravindrayr** [comment]
Thank you  it was mistake form myside, i had set in below props,which was stoping date-range to work,thanks for the response.

   :from="datepickerSetting.fromDate"
    :to="datepickerSetting.toDate"
