### ISSUE TITLE
 Clicked clear value then reopen datepicker yearMinus have some problem.

### ISSUE THREAD

**Issue by gottenwit** [linmasahiro/vue3-datepicker-lite#19]
Hi , I have some problem with yearMinus. When I clicked clear then reopen datepicker yearMinus have some problem.

Library Version : 1.9.2

![image](https://user-images.githubusercontent.com/52517915/144209182-39db008b-46f5-457e-8c2a-e05d5ec5e6e9.png)

My Settings
```
const datepickerSetting = {
      class: "myDateInput",
      value: "01/12/2564",
      placeholder: "โปรดเลือก",
      yearMinus: -543,
      fromDate: "02/10/2400",
      toDate: "",
      disabledDate: [],
      locale: {
        format: "DD/MM/YYYY",
        weekday: ["อา", "จ", "อ", "พ", "พฤ", "ศ", "ส"],
        startsWeeks: 0,
        todayBtn: "Today",
        clearBtn: "Clear",
        closeBtn: "Close"
      },
      changeEvent: value => {
        return value;
      },
      disableInput: false
    };
```

Thank You So Much.

**Comment by linmasahiro** [comment]
#20

**Comment by linmasahiro** [comment]
Hi, @gottenwit 
Thank you for response. I am already fixed the bug on v1.9.4.
Please upgrade to v1.9.4.
Btw, yearMinus can't use minus number, please edit it like
```
const datepickerSetting = {
      class: "myDateInput",
      value: "01/12/2564",
      placeholder: "โปรดเลือก",
      yearMinus: 543,
      fromDate: "02/10/2400",
      toDate: "",
      disabledDate: [],
      locale: {
        format: "DD/MM/YYYY",
        weekday: ["อา", "จ", "อ", "พ", "พฤ", "ศ", "ส"],
        startsWeeks: 0,
        todayBtn: "Today",
        clearBtn: "Clear",
        closeBtn: "Close"
      },
      changeEvent: value => {
        return value;
      },
      disableInput: false
    };
```

**Comment by gottenwit** [comment]
> Hi, @gottenwit Thank you for response. I am already fixed the bug on v1.9.4. Please upgrade to v1.9.4. Btw, yearMinus can't use minus number, please edit it like
> 
> ```
> const datepickerSetting = {
>       class: "myDateInput",
>       value: "01/12/2564",
>       placeholder: "โปรดเลือก",
>       yearMinus: 543,
>       fromDate: "02/10/2400",
>       toDate: "",
>       disabledDate: [],
>       locale: {
>         format: "DD/MM/YYYY",
>         weekday: ["อา", "จ", "อ", "พ", "พฤ", "ศ", "ส"],
>         startsWeeks: 0,
>         todayBtn: "Today",
>         clearBtn: "Clear",
>         closeBtn: "Close"
>       },
>       changeEvent: value => {
>         return value;
>       },
>       disableInput: false
>     };
> ```

Hi, @linmasahiro 
Thank you for your response and fixed. But I'm not sure when updated library to version 1.9.3 or 1.9.4.
I build failed project.

info using npm@7.3.0
info using node@v15.5.1
![image](https://user-images.githubusercontent.com/52517915/144371769-a50b1020-1bad-414f-a42f-27a55823ef51.png)

package.json
![image](https://user-images.githubusercontent.com/52517915/144372158-e42a02ec-27ff-4b58-81fd-7c212dadf85c.png)
![image](https://user-images.githubusercontent.com/52517915/144372172-21599040-837f-4ec4-91f7-6f4a0093ca07.png)

node_modules
![image](https://user-images.githubusercontent.com/52517915/144372503-8c65fdc8-ff5e-4cd5-b7e6-11fb3bd5a367.png)

**Comment by linmasahiro** [comment]
@gottenwit 

> Thank you for your response and fixed. But I'm not sure when updated library to version 1.9.3 or 1.9.4.
I build failed project.

I am so sorry for uploaded wrong index.js file. :(
I made a big mistake. I am uploaded again. please update to 1.9.6.

```
import DatepickerLite from "vue3-datepicker-lite";     // For JavaScript
import DatepickerLite from "vue3-datepicker-lite/ts";  // For TypeScript
```

**Comment by gottenwit** [comment]
@linmasahiro 
Thank you. I have new issue. 😄 

Library Version : 1.9.6

![image](https://user-images.githubusercontent.com/52517915/144445582-7de42929-5e4b-420e-bd33-b0d0510ee25a.png)

**Comment by linmasahiro** [comment]
> @linmasahiro Thank you. I have new issue. 😄

Hi, you can skip the error message and build your project. I think it will be work with no problem. 
Or fix yourself like this.
```
const select = (value) => {
  if (value) {
    let tmp = value.match(formatSetting.formatRegexp);
    ...
  }
}
```

**Comment by gottenwit** [comment]
> > @linmasahiro Thank you. I have new issue. 😄
> 
> Hi, you can skip the error message and build your project. I think it will be work with no problem. Or fix yourself like this.
> 
> ```
> const select = (value) => {
>   if (value) {
>     let tmp = value.match(formatSetting.formatRegexp);
>     ...
>   }
> }
> ```

@linmasahiro Thank you so much. I tested work perfectly.

Fixed
#21
