### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by juanmanavarro** [linmasahiro/vue3-datepicker-lite#3]
Hi. Is it possible to change the date format to DD/MM/YYYY in the input?

**Comment by linmasahiro** [comment]
> Hi. Is it possible to change the date format to DD/MM/YYYY in the input?

Hi, i added change dateformat function. please upgrade to v1.6.0 and enjoy it.

refrence [demo](https://linmasahiro.github.io/vue3-datepicker-lite/dist/)

**Comment by juanmanavarro** [comment]
Thank you!
