### ISSUE TITLE
From date is incorrectly calculated

### ISSUE THREAD

**Issue by sivabudati** [linmasahiro/vue3-datepicker-lite#6]
Hello,

Thank you for the library. For me, from date setting is not working. For the setting object below, I can navigate to January, February, and March, but all dates in January and February are disabled. Only March is enabled. To Date and Disabled dates work as expected. Can you help please? Thank you.

datepickerSetting: {
                id: "birthday",
                name: "birthday",
                class: "myDateInput",
                value: "2021/01/09",
                placeholder: "Select",
                yearMinus: 0,
                fromDate: "2021/01/02",
                toDate: "2021/03/31",
                disabledDate: [
                    "2021/03/02",
                    "2021/03/19",
                ],
                locale: {
                    format: "YYYY/MM/DD",
                    weekday: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
                    todayBtn: "Today",
                    clearBtn: "Clear",
                    closeBtn: "Close",
                },
                changeEvent: (value) => {
                    console.log(value + " selected!");
                },
                disableInput: false,
            }

**Comment by sivabudati** [comment]
I think I found the issue: **Line 322** in _src/components/DatepickerLite.vue_ should be changed from
`(yyyy == fromDate[formatSetting.yearIndex] && mm < toDate[formatSetting.monthIndex]) ||`
to
`(yyyy == fromDate[formatSetting.yearIndex] && mm < fromDate[formatSetting.monthIndex]) ||`

Please check my pull requests with fixed code. I didn't know whether to do `npm run build` or not. So, I created two pull requests - one with and one without. Source changes are the same in both. Thank you.

**Comment by linmasahiro** [comment]
> I think I found the issue: **Line 322** in _src/components/DatepickerLite.vue_ should be changed from
> `(yyyy == fromDate[formatSetting.yearIndex] && mm < toDate[formatSetting.monthIndex]) ||`
> to
> `(yyyy == fromDate[formatSetting.yearIndex] && mm < fromDate[formatSetting.monthIndex]) ||`
> 
> Please check my pull requests with fixed code. I didn't know whether to do `npm run build` or not. So, I created two pull requests - one with and one without. Source changes are the same in both. Thank you.

Hello!

thank you for pull request! it's good fixed! 👍 

this request help to me found other bug(disabledDate not working for other date format) and fixed it. 

thank you very much!!
