### ISSUE TITLE
Start weeks on monday

### ISSUE THREAD

**Issue by XanderTenBoden** [linmasahiro/vue3-datepicker-lite#9]
Hello there! Is it someway possible to change the first day of the week to monday instead of sunday? :)

**Comment by linmasahiro** [comment]
> Hello there! Is it someway possible to change the first day of the week to monday instead of sunday? :)

Hi

i added startsWeeks option into locale options. you can change first day of the week on ver 1.8.4.

sample:

```
locale: {
  format: "YYYY/MM/DD",
  weekday: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  startsWeeks: 1,
  todayBtn: "Today",
  clearBtn: "Clear",
  closeBtn: "Close",
}
```

**Comment by XanderTenBoden** [comment]
Hmm I think something went wrong there. The calendar is now empty for me.
![Screenshot 2021-01-15 at 10 51 45](https://user-images.githubusercontent.com/6901151/104709928-c2477e00-571f-11eb-953b-b116c7a620bb.png)

**Comment by linmasahiro** [comment]
> Hmm I think something went wrong there. The calendar is now empty for me.
> ![Screenshot 2021-01-15 at 10 51 45](https://user-images.githubusercontent.com/6901151/104709928-c2477e00-571f-11eb-953b-b116c7a620bb.png)

can you give  me your setting data?

**Comment by XanderTenBoden** [comment]
`{
          format: 'DD-MM-YYYY',
          weekday: [
            'Mon',
            'Tue',
            'Wed',
            'Thu',
            'Fri',
            'Sat',
            'Sun',
          ],
          // startsWeek: 1,
          todayBtn: 'Today',
          clearBtn: 'Clear',
          closeBtn: 'Close',
        }`

**Comment by linmasahiro** [comment]
> DD-MM-YYYY

thanks.

i try this setting on my code. it's working.

i already put it on codesandbox. you can see it.

sample code URL : https://codesandbox.io/s/nostalgic-river-nd5r2?fontsize=14&hidenavigation=1&theme=dark

**Comment by XanderTenBoden** [comment]
I'm not sure what is causing this issue for me.

When I posted the original request, vue3-datepicker-lite was working correctly for me. The next morning I saw your comment and updated to 1.8.4 after which the addon stopped working. I've now reverted the addon back to 1.8.3, and it is still not showing any days. Deleting my node_modules does not solve the issue either. Any suggestions what the issue might be? I've kinda ran out of ideas.

**Comment by XanderTenBoden** [comment]
Alright, I figured it out.

I used "startWeek" instead of "startWeeks". This was the reason the function was not checking my setting.

However, that also means that there is actually a bug which causes the calendar to stop functioning properly if the startWeeks property was not provided. I've already found the cause of this, I will submit a MR :)

**Comment by linmasahiro** [comment]
> Alright, I figured it out.
> 
> I used "startWeek" instead of "startWeeks". This was the reason the function was not checking my setting.
> 
> However, that also means that there is actually a bug which causes the calendar to stop functioning properly if the startWeeks property was not provided. I've already found the cause of this, I will submit a MR :)

Thanks! it's good news!

I think ... this bug maybe not only "startWeeks" property. so i fixed the bug when lost any property on locale attribute was provided and committed to ver 1.8.5

**Comment by XanderTenBoden** [comment]
Awesome, thanks for the update!
